//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServerRM.rc
//
#define IDB_SGM_RET_STOP                3
#define IDB_SGM_RT_FIRST                7
#define IDB_SGM_RT_PREV                 8
#define IDCANCEL7                       11
#define IDB_SGM_RT_LAST                 11
#define IDB_SGM_RT_NEXT                 12
#define IDM_MAIN_WINDOW                 101
#define IDD_ADD_CLIENT                  102
#define IDC_MAIN_WINDOW                 103
#define IDD_ADD_PLUGIN                  105
#define IDD_REM_PLUGIN                  106
#define IDD_VIEW_PLUGINS                107
#define IDD_VIEW_CLIENTS                108
#define IDD_VIEW_REM_CLIENTS            108
#define IDD_REM_CLIENT                  110
#define IDD_CONNECT_TO                  111
#define IDD_KLM_RT                      112
#define IDD_KLM_RETRIEVE                113
#define IDD_KLM_OFFLINE                 114
#define IDD_KLM_CONFIG                  115
#define IDD_KLM                         117
#define IDD_SGM                         118
#define IDD_SGM_RT                      120
#define IDD_SGM_OFFLINE                 121
#define IDD_SGM_RETRIEVE                122
#define IDD_SGM_CONFIG                  123
#define IDD_FBM                         124
#define IDD_FBM_UI                      125
#define IDD_SCAN_IP_ADDR                126
#define IDD_SCAN_IP_RESULT              127
#define IDD_EDIT_NICKNAME               128
#define IDD_ABOUT                       129
#define IDI_FOLDER_CLOSED               130
#define IDI_FOLDER_OPEN                 132
#define IDB_BITMAP1                     133
#define IDB_BITMAP2                     134
#define IDB_BITMAP3                     135
#define IDB_BITMAP4                     136
#define IDC_ADD_CLIENT_IP               1001
#define IDC_SCAN_IP_ADDR_TO             1002
#define IDC_ADD_PLUGIN_PATH             1003
#define IDC_KLM_CONFIG_EDIT1            1003
#define IDC_KLM_CONFIG_RT_INT           1003
#define IDC_ADD_PLUGIN_NAME             1004
#define IDC_KLM_CANCEL                  1004
#define IDC_VIEW_PLUGINS_LIST           1005
#define ID_SGM_CANCEL                   1005
#define IDB_SGM_CANCEL                  1005
#define IDC_ADD_PLUGIN_NAME2            1005
#define IDC_ADD_PLUGIN_IF_NAME          1005
#define IDC_VIEW_REM_PLUGINS_LIST       1005
#define IDB_ADD_PLUGIN_BROWSE           1006
#define IDC_KLM_TAB                     1006
#define IDC_ADD_PLUGIN_PID              1007
#define IDC_SGM_TAB                     1009
#define IDC_SGM_RT_COMBO                1010
#define IDB_ADD_CLIENT_ADD              1011
#define IDB_SGM_RT_START                1011
#define IDB_ADD_PLUGIN_ADD              1012
#define IDC_SGM_RT_TREE                 1012
#define IDB_ADD_PLUGIN_CANCEL           1013
#define IDC_SGM_RT_IMG                  1013
#define IDB_REMOVE_CLIENT               1014
#define IDB_SGM_RT_STOP                 1014
#define IDB_ADD_CLIENT_CANCEL           1015
#define IDB_KLM_RET_GETFILES            1015
#define IDB_ADD_CLIENT_RESET            1016
#define IDB_KLM_RET_STOP                1016
#define IDB_CONNECT_TO                  1017
#define IDC_SGM_OFF_TREE                1017
#define IDB_CONNECT_CANCEL              1018
#define IDC_SGM_OFF_PIC                 1018
#define IDB_REM_CLIENT_CANCEL           1019
#define IDB_SGM_RET_RETRIEVE            1019
#define IDB_REMOVE_PLUGIN               1020
#define IDC_SGM_CONFIG_RT_INT           1020
#define IDB_REM_PLUGIN_CANCEL           1021
#define IDC_SGM_CONFIG_OFF_INT          1021
#define IDB_VIEW_CLIENTS_OK             1022
#define IDC_SGM_CONFIG_AS               1022
#define IDC_SGM_CONFIG_MS               1023
#define IDB_SCAN_IP_RESULT_ADD          1023
#define IDB_VIEW_CLIENTS_EDIT           1023
#define IDB_EDIT_NICKNAME_OK            1023
#define IDB_VIEW_PLUGINS_OK             1024
#define IDC_SGM_CONFIG_FS               1024
#define IDB_SCAN_IP_RESULT_ADD2         1024
#define IDB_SCAN_IP_RESULT_CONNECT      1024
#define IDC_ADD_CLIENT_NAME             1025
#define IDC_PROGRESS1                   1025
#define IDC_KLM_RET_PROGRESS            1025
#define IDC_FBM_UI_PROGRESS             1025
#define IDC_SGM_RET_PROGRESS            1025
#define IDC_CONNECT_TO_LIST             1026
#define IDC_CUSTOM1                     1026
#define IDC_REMOVE_CLIENT_LIST          1027
#define IDC_SGM_OFF_STATIC              1027
#define IDC_VIEW_REM_CLIENT_LIST        1027
#define IDC_FBM_TAB                     1028
#define IDC_REMOVE_PLUGIN_LIST          1029
#define IDC_VIEW_REM_PLUGIN_LIST        1029
#define IDB_FBM_CANCEL                  1029
#define IDC_VIEW_CLIENTS_LIST           1030
#define IDC_VIEW_REM_CLIENTS_LIST       1030
#define IDC_FBM_UI_TREE                 1030
#define IDC_KLM_RT_EDIT_SEARCH          1031
#define IDC_KLM_RET_STATIC              1031
#define IDB_KLM_RT_FINDNEXT             1032
#define IDC_FBM_UI_STATIC               1032
#define IDC_KLM_RT_TREE                 1033
#define IDC_SGM_RET_STATIC              1033
#define IDC_KLM_RT_EDIT_ATITLE          1034
#define IDC_SCAN_IP_ADDR_FROM           1034
#define IDC_KLM_RT_EDIT_DATA            1035
#define IDB_SCAN_IP_ADDR_SCAN           1035
#define IDC_KLM_RT_EDIT_KEYS            1035
#define IDB_KLM_RT_START                1036
#define IDB_SCAN_IP_ADDR_RESET          1036
#define IDB_KLM_RT_STOP                 1037
#define IDB_SCAN_UI_CANCEL              1037
#define IDB_SCAN_IP_ADDR_CANCEL         1037
#define IDC_KLM_OFF_COMBO               1038
#define IDC_KLM_RT_EDIT_ATITLE2         1038
#define IDC_SCAN_IP_RESULT_LIST         1038
#define IDB_KLM_OFF_BUILD               1039
#define IDB_SCAN_IP_RESULT_CANCEL       1039
#define IDC_KLM_OFF_EDIT_SEARCH         1040
#define IDC_SCAN_IP_ADDR_STATIC         1040
#define IDB_KLM_OFF_FINDNEXT            1041
#define IDC_KLM_OFF_TREE                1042
#define IDC_EDIT_NICKNAME_EDIT          1042
#define IDB_KLM_OFF_STOP                1043
#define IDB_EDIT_NICKNAME_CANCEL        1043
#define IDC_KLM_OFF_EDIT_ATITLE         1044
#define IDC_KLM_CONFIG_APP_LIST         1044
#define IDC_KLM_OFF_EDIT_DATA           1045
#define IDC_KLM_OFF_EDIT_KEYS           1045
#define IDC_SGM_RT_STATUS               1045
#define IDC_DATETIMEPICKER1             1046
#define IDC_KLM_RET_FROMDATE            1046
#define IDC_SGM_RET_FROMDATE            1046
#define IDC_ABOUT_LOGO                  1046
#define IDC_DATETIMEPICKER2             1047
#define IDC_KLM_RET_TODATE              1047
#define IDC_SGM_RET_TODATE              1047
#define IDC_KLM_OFF_EDIT_ATITLE2        1047
#define IDC_EDIT2                       1048
#define IDC_KLM_CONFIG_EDIT2            1048
#define IDC_SGM_CONFIG_ADD_APP          1048
#define IDC_KLM_CONFIG_OFF_INT          1048
#define IDC_EDIT3                       1049
#define IDC_KLM_CONFIG_EDIT3            1049
#define IDC_KLM_CONFIG_ADDAPP           1049
#define IDC_KLM_CONFIG_ADD_APP          1049
#define IDC_BUTTON1                     1050
#define IDB_KLM_CONFIG_ADD              1050
#define IDC_SGM_OFF_FIRST               1050
#define IDB_SGM_CONFIG_ADD              1050
#define IDB_FBM_UI_COPY                 1050
#define IDB_ABOUT_OK                    1050
#define IDC_LIST1                       1051
#define IDC_KLM_CONFIG_APPLIST          1051
#define IDC_SGM_OFF_NEXT                1051
#define IDC_SGM_RET_APPLIST             1051
#define IDC_SGM_CONFIG_APPLIST          1051
#define IDC_FBM_UI_LIST                 1051
#define IDC_BUTTON2                     1052
#define IDB_KLM_CONFIG_UREMOTE          1052
#define IDC_SGM_OFF_PREV                1052
#define IDB_SGM_CONFIG_UREMOTE          1052
#define IDB_FBM_UI_CANCEL_COPY          1052
#define IDC_SGM_OFF_LAST                1053
#define IDB_FBM_UI_START                1053
#define IDM_CLIENTDB_ADD                40042
#define IDM_CLIENTDB_REMOVE             40043
#define IDM_CLIENTDB_VIEWCLIENTS        40044
#define IDM_PLUGINDB_ADD                40045
#define IDM_PLUGINDB_REMOVE             40046
#define IDM_PLUGINDB_VIEWPLUGINS        40047
#define IDM_SERVERCONFIG_EXIT           40048
#define IDM_MONITOR_CONNECT             40049
#define IDM_MONITOR_INSTALLPLUGIN       40050
#define IDM_MONITOR_UNINSTALLPLUGIN     40051
#define IDM_LAUNCHPLUGIN_KL             40052
#define IDM_LAUNCHPLUGIN_SG             40053
#define IDM_LAUNCHPLUGIN_FB             40054
#define IDM_MONITOR_DISCONNECT          40055
#define IDM_HELP_CONTENTS               40056
#define IDM_HELP_ABOUT                  40057
#define IDM_LAUNCH                      40058
#define ID_LAUNCHPLUGIN_KLM             40059
#define IDM_LAUNCHPLUGIN_KLM            40060
#define ID_LAUNCHPLUGIN_SGM             40061
#define IDM_LAUNCHPLUGIN_SGM            40062
#define ID_LAUNCHPLUGIN_FBM             40063
#define IDM_LAUNCHPLUGIN_FBM            40064
#define ID_MONITOR_LAUNCHPLUGIN         40065
#define IDM_MONITOR_LAUNCHPLUGIN        40066
#define ID_LAUNCHPLUGIN_KLM40067        40067
#define ID_LAUNCHPLUGIN_SGM40068        40068
#define ID_LAUNCHPLUGIN_FBM40069        40069
#define ID_MONITOR_SCANIPS              40070
#define IDM_MONITOR_SCAN_IP             40071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         40072
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
